#!/usr/bin/env bash

tmax_load_run_state() {
    local state_file="$1"
    [ -s "$state_file" ] || return 1
    # The state file is generated by tmax_write_run_state with shell-escaped values.
    # shellcheck source=/dev/null
    source "$state_file"
    [ -n "${RUN_ID:-}" ] && [ -n "${SAVE_DIR:-}" ]
}

tmax_write_run_state() {
    local state_file="$1"
    local tmp_file="${state_file}.tmp.$$"
    local name
    local -a names=(
        RUN_ID SAVE_DIR SLIME_ROLLOUT_BASE_PORT TRAINING_COMPLETE_MARKER
        TMAX_TRAIN_DATA TMAX_MAX_TASKS TMAX_ONLY_READY TMAX_PREPARE_DATA
        ROLLOUT_BATCH_SIZE N_SAMPLES_PER_PROMPT NUM_EPOCH SAVE_INTERVAL
        TMAX_TARGET_ITER WALL_TIME TMAX_ENABLE_GRACEFUL_EXIT
        TMAX_GRACEFUL_EXIT_BUFFER_SECONDS EXPERIMENT_NAME
        WANDB_PROJECT WANDB_GROUP WANDB_RESUME
    )

    mkdir -p "$(dirname "$state_file")"
    umask 077
    : >"$tmp_file"
    for name in "${names[@]}"; do
        if [ -n "${!name+x}" ]; then
            printf 'export %s=%q\n' "$name" "${!name}" >>"$tmp_file"
        fi
    done
    chmod 600 "$tmp_file"
    mv "$tmp_file" "$state_file"
}
