"""Durable write-ahead log for an interrupted Polar rollout batch.

The model checkpoint remains the training commit marker.  This module only
persists prompt-reservation decisions made while building the *next* batch so
that a process restart can reconstruct reservations from the exact checkpoint
frontier and reuse whole, already-validated GRPO groups.

The WAL is deliberately enabled only for the first rollout after a durable
checkpoint and only while the rollout worker is still empty.  Reusing samples
generated by an uncheckpointed policy would be unsafe.
"""

from __future__ import annotations

import dataclasses
import enum
import hashlib
import importlib.util
import json
import logging
import math
import os
from pathlib import Path
import shutil
import threading
import time
from typing import Any, Iterable

import torch


logger = logging.getLogger(__name__)

PARTIAL_ROLLOUT_WAL_VERSION = 1
STATE_PREPARED = "PREPARED"
STATE_RESULT_READY = "RESULT_READY"
STATE_KEEP = "KEEP"
STATE_DROP = "DROP"
_VALID_STATES = frozenset({STATE_PREPARED, STATE_RESULT_READY, STATE_KEEP, STATE_DROP})
_RESULT_STATES = frozenset({STATE_RESULT_READY, STATE_KEEP})
_SECRET_KEY_PARTS = (
    "api_key",
    "authorization",
    "credential",
    "password",
    "secret",
)
_SEMANTIC_TOKEN_KEY_PARTS = (
    "budget",
    "completion",
    "length",
    "max_",
    "min_",
    "num_",
    "prompt",
    "response",
    "trajectory",
)


class PartialRolloutError(RuntimeError):
    """Raised when a partial-rollout WAL cannot be trusted."""


@dataclasses.dataclass(frozen=True, slots=True)
class PartialRolloutHeader:
    run_id: str
    rollout_id: int
    base_checkpoint_iteration: int
    base_checkpoint_digest: str
    config_digest: str
    target_groups: int

    def to_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


def _fsync_directory(path: Path) -> None:
    directory_fd = os.open(path, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
    try:
        os.fsync(directory_fd)
    finally:
        os.close(directory_fd)


def _atomic_torch_save(payload: Any, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f"{path.name}.tmp.{os.getpid()}.{threading.get_ident()}")
    try:
        with open(temporary, "wb") as stream:
            torch.save(payload, stream)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
        _fsync_directory(path.parent)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as stream:
        while chunk := stream.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def _is_secret_key(key: str) -> bool:
    normalized = key.lower()
    if normalized in {"auth", "headers", "token"}:
        return True
    if any(part in normalized for part in _SECRET_KEY_PARTS):
        return True
    return normalized.endswith("_token") and not any(
        part in normalized for part in _SEMANTIC_TOKEN_KEY_PARTS
    )


def _canonicalize(value: Any, *, key: str | None = None) -> Any:
    if key is not None and _is_secret_key(key):
        return "<redacted>"
    if dataclasses.is_dataclass(value):
        return _canonicalize(dataclasses.asdict(value))
    if isinstance(value, enum.Enum):
        return _canonicalize(value.value)
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {
            str(item_key): _canonicalize(item_value, key=str(item_key))
            for item_key, item_value in sorted(value.items(), key=lambda item: str(item[0]))
        }
    if isinstance(value, (list, tuple)):
        return [_canonicalize(item) for item in value]
    if isinstance(value, set):
        return sorted(_canonicalize(item) for item in value)
    if isinstance(value, float):
        if math.isnan(value):
            return "<nan>"
        if math.isinf(value):
            return "<+inf>" if value > 0 else "<-inf>"
        return value
    if isinstance(value, (str, int, bool)) or value is None:
        return value
    if hasattr(value, "tolist"):
        try:
            return _canonicalize(value.tolist())
        except Exception:
            pass
    return repr(value)


def _canonical_digest(value: Any) -> str:
    encoded = json.dumps(
        _canonicalize(value),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def prompt_group_digest(group: list[Any]) -> str:
    """Hash stable prompt-origin fields, excluding generated runtime output."""

    fields = (
        "group_index",
        "index",
        "rollout_id",
        "prompt",
        "tokens",
        "label",
        "metadata",
        "generate_function_path",
        "custom_rm_path",
        "session_id",
    )
    payload = [{field: getattr(sample, field, None) for field in fields} for sample in group]
    return _canonical_digest(payload)


def _sample_to_dict(sample: Any) -> dict[str, Any]:
    converter = getattr(sample, "to_dict", None)
    if callable(converter):
        value = converter()
    elif dataclasses.is_dataclass(sample):
        value = dataclasses.asdict(sample)
    elif hasattr(sample, "__dict__"):
        value = dict(sample.__dict__)
    else:
        raise PartialRolloutError(
            f"cannot serialize recovered sample of type {type(sample).__name__}"
        )
    if not isinstance(value, dict):
        raise PartialRolloutError("sample serializer did not return a mapping")
    return value


def partial_rollout_config_digest(args: Any, config: Any) -> str:
    """Fingerprint every semantic input needed to trust persisted samples."""

    config_payload = dataclasses.asdict(config) if dataclasses.is_dataclass(config) else {}
    # Transport endpoints and callback bindings are expected to change across
    # Slurm allocations; they do not change the semantics of an existing result.
    for transport_field in ("rollout_server_url", "callback_host", "request_timeout"):
        config_payload.pop(transport_field, None)
    _normalize_allocation_transport(config_payload.get("task_template"))

    semantic_arg_names = (
        "calculate_per_token_loss",
        "context_parallel_size",
        "custom_rm_path",
        "custom_reward_post_process_path",
        "custom_rollout_log_function_path",
        "dynamic_sampling_filter_path",
        "hf_checkpoint",
        "max_tokens_per_gpu",
        "n_samples_per_prompt",
        "polar_allow_single_sample_over_token_cap",
        "polar_max_trajectory_tokens",
        "reward_key",
        "rollout_batch_size",
        "rollout_max_prompt_len",
        "rollout_max_response_len",
        "rollout_shuffle",
        "seq_length",
        "update_weights_interval",
    )
    semantic_args = {name: getattr(args, name, None) for name in semantic_arg_names}
    provenance = {
        name: os.environ.get(name)
        for name in (
            "TMAX_MEGATRON_GIT_COMMIT",
            "TMAX_PRORL_GIT_COMMIT",
            "TMAX_SLIME_GIT_COMMIT",
        )
    }
    source_digests = {
        "partial_rollout": _sha256_file(Path(__file__)),
        "rollout_bridge": _sha256_file(Path(__file__).with_name("rollout.py")),
        "adapter": _sha256_file(Path(__file__).with_name("adapter.py")),
    }
    for name in (
        "custom_rm_path",
        "custom_reward_post_process_path",
        "dynamic_sampling_filter_path",
    ):
        symbol_path = getattr(args, name, None)
        if symbol_path:
            source_digests[name] = _symbol_source_digest(str(symbol_path))
    return _canonical_digest(
        {
            "config": config_payload,
            "args": semantic_args,
            "provenance": provenance,
            "source_digests": source_digests,
        }
    )


def _normalize_allocation_transport(task_template: Any) -> None:
    """Remove per-allocation addresses while retaining task/model semantics."""

    if not isinstance(task_template, dict):
        return
    runtime = task_template.get("runtime")
    if not isinstance(runtime, dict):
        return
    env = runtime.get("env")
    if isinstance(env, dict):
        for key in list(env):
            if "proxy" in str(key).lower():
                env.pop(key, None)

    def normalize_mounts(value: Any) -> Any:
        if not isinstance(value, list):
            return value
        normalized = []
        for mount in value:
            if isinstance(mount, str) and (":/polar/gateway" in mount or ":/polar/proxy" in mount):
                _host, separator, container_spec = mount.partition(":")
                normalized.append(f"<allocation-transport>{separator}{container_spec}")
            else:
                normalized.append(mount)
        return normalized

    kwargs = runtime.get("kwargs")
    if isinstance(kwargs, dict) and "volumes" in kwargs:
        kwargs["volumes"] = normalize_mounts(kwargs["volumes"])
    if "internet_volumes" in runtime:
        runtime["internet_volumes"] = normalize_mounts(runtime["internet_volumes"])


def _symbol_source_digest(symbol_path: str) -> str:
    module_name, separator, _attribute = symbol_path.rpartition(".")
    if not separator:
        return "<invalid-symbol-path>"
    try:
        spec = importlib.util.find_spec(module_name)
    except (ImportError, ModuleNotFoundError, ValueError):
        return "<module-unavailable>"
    if spec is None or not spec.origin:
        return "<module-unavailable>"
    origin = Path(spec.origin)
    if not origin.is_file():
        return "<source-unavailable>"
    return _sha256_file(origin)


def _checkpoint_digest(root: Path, iteration: int) -> str | None:
    tracker = root / "latest_checkpointed_iteration.txt"
    data_state = root / "rollout" / f"global_dataset_state_dict_{iteration}.pt"
    iteration_dir = root / f"iter_{iteration:07d}"
    model_metadata = iteration_dir / ".metadata"
    common_state = iteration_dir / "common.pt"
    required = (tracker, data_state, model_metadata, common_state)
    if not all(path.is_file() for path in required):
        return None
    try:
        tracker_value = tracker.read_text(encoding="utf-8").strip()
    except OSError:
        return None
    if tracker_value != str(iteration):
        return None

    digest = hashlib.sha256()
    digest.update(f"iteration={iteration}\n".encode())
    for path in required:
        digest.update(path.name.encode())
        digest.update(b"\0")
        digest.update(_sha256_file(path).encode())
        digest.update(b"\n")
    return digest.hexdigest()


def maybe_open_partial_rollout_store(
    args: Any,
    config: Any,
    rollout_id: int,
) -> "PartialRolloutStore | None":
    """Open the one safe WAL: the first batch after an exact model checkpoint."""

    if not bool(getattr(args, "rollout_global_dataset", False)):
        return None
    if int(getattr(args, "start_rollout_id", -1) or 0) != int(rollout_id):
        return None
    if rollout_id <= 0:
        return None
    save_root_raw = getattr(args, "save", None)
    load_root_raw = getattr(args, "load", None)
    if not save_root_raw or not load_root_raw:
        return None

    base_iteration = int(rollout_id) - 1
    checkpoint_digest = _checkpoint_digest(Path(load_root_raw), base_iteration)
    if checkpoint_digest is None:
        logger.warning(
            "Partial rollout recovery disabled for rollout %s: exact durable "
            "checkpoint %s is unavailable",
            rollout_id,
            base_iteration,
        )
        return None

    run_id = str(
        os.environ.get("RUN_ID")
        or getattr(args, "wandb_group", None)
        or getattr(args, "experiment_name", None)
        or ""
    ).strip()
    if not run_id:
        logger.warning("Partial rollout recovery disabled: stable run id is unavailable")
        return None

    header = PartialRolloutHeader(
        run_id=run_id,
        rollout_id=int(rollout_id),
        base_checkpoint_iteration=base_iteration,
        base_checkpoint_digest=checkpoint_digest,
        config_digest=partial_rollout_config_digest(args, config),
        target_groups=int(getattr(args, "rollout_batch_size", 1) or 1),
    )
    directory = (
        Path(save_root_raw) / "rollout" / "partial_rollout_wal" / f"rollout_{int(rollout_id):07d}"
    )
    _gc_committed_partial_rollouts(
        directory.parent,
        committed_iteration=base_iteration,
        current_rollout_id=int(rollout_id),
    )
    return PartialRolloutStore(directory, header)


def _gc_committed_partial_rollouts(
    parent: Path,
    *,
    committed_iteration: int,
    current_rollout_id: int,
) -> None:
    """Delete WALs whose matching model iteration is already durable."""

    if not parent.is_dir():
        return
    for path in parent.glob("rollout_[0-9][0-9][0-9][0-9][0-9][0-9][0-9]"):
        try:
            rollout_id = int(path.name.removeprefix("rollout_"))
        except ValueError:
            continue
        if rollout_id >= current_rollout_id or rollout_id > committed_iteration:
            continue
        tombstone = path.with_name(f"{path.name}.gc.{time.time_ns()}.{os.getpid()}")
        try:
            os.replace(path, tombstone)
            _fsync_directory(parent)
            shutil.rmtree(tombstone)
            _fsync_directory(parent)
        except FileNotFoundError:
            continue
        except Exception:
            logger.exception("Failed to garbage-collect committed partial WAL %s", path)


class PartialRolloutStore:
    """Thread-safe, per-rollout reservation decision WAL."""

    def __init__(self, directory: Path, header: PartialRolloutHeader) -> None:
        self.directory = Path(directory)
        self.header = header
        self._lock = threading.RLock()
        self._sealed = False

    @property
    def sealed(self) -> bool:
        with self._lock:
            return self._sealed

    def _record_path(self, reservation_id: int) -> Path:
        return self.directory / f"reservation_{int(reservation_id):020d}.pt"

    def _ready_path(self) -> Path:
        return self.directory / "READY.pt"

    def _base_record(
        self,
        *,
        reservation_id: int,
        state: str,
        prompt_digest: str,
        submitted_rollout_id: int,
        policy_version: int,
        group_size: int,
    ) -> dict[str, Any]:
        return {
            "version": PARTIAL_ROLLOUT_WAL_VERSION,
            "header": self.header.to_dict(),
            "reservation_id": int(reservation_id),
            "state": state,
            "prompt_digest": str(prompt_digest),
            "submitted_rollout_id": int(submitted_rollout_id),
            "policy_version": int(policy_version),
            "group_size": int(group_size),
            "updated_unix_ns": time.time_ns(),
        }

    @staticmethod
    def _with_record_digest(record: dict[str, Any]) -> dict[str, Any]:
        record = dict(record)
        record.pop("record_digest", None)
        record["record_digest"] = _canonical_digest(record)
        return record

    @staticmethod
    def _validate_record_digest(record: dict[str, Any], path: Path) -> None:
        expected = record.get("record_digest")
        unsigned = dict(record)
        unsigned.pop("record_digest", None)
        actual = _canonical_digest(unsigned)
        if not isinstance(expected, str) or expected != actual:
            raise PartialRolloutError(f"record digest mismatch: {path}")

    def _load_record(self, reservation_id: int) -> dict[str, Any] | None:
        path = self._record_path(reservation_id)
        if not path.exists():
            return None
        try:
            record = torch.load(path, weights_only=False)
        except Exception as exc:
            raise PartialRolloutError(f"cannot load partial record {path}: {exc}") from exc
        self._validate_record(record, path)
        return record

    def _validate_record(self, record: Any, path: Path) -> None:
        if not isinstance(record, dict):
            raise PartialRolloutError(f"partial record is not a mapping: {path}")
        if record.get("version") != PARTIAL_ROLLOUT_WAL_VERSION:
            raise PartialRolloutError(f"unsupported partial record version: {path}")
        if record.get("header") != self.header.to_dict():
            raise PartialRolloutError(f"partial record header mismatch: {path}")
        if record.get("state") not in _VALID_STATES:
            raise PartialRolloutError(f"invalid partial record state: {path}")
        try:
            reservation_id = int(record["reservation_id"])
            submitted_rollout_id = int(record["submitted_rollout_id"])
            policy_version = int(record["policy_version"])
            group_size = int(record["group_size"])
        except (KeyError, TypeError, ValueError) as exc:
            raise PartialRolloutError(f"invalid partial record integer field: {path}") from exc
        if path.name != self._record_path(reservation_id).name:
            raise PartialRolloutError(f"reservation filename mismatch: {path}")
        if group_size <= 0:
            raise PartialRolloutError(f"invalid partial record group size: {path}")
        if submitted_rollout_id != self.header.rollout_id:
            raise PartialRolloutError(f"partial record submitted rollout mismatch: {path}")
        if policy_version != self.header.rollout_id:
            raise PartialRolloutError(f"partial record policy version mismatch: {path}")
        prompt_digest = record.get("prompt_digest")
        if not isinstance(prompt_digest, str) or len(prompt_digest) != 64:
            raise PartialRolloutError(f"invalid partial prompt digest: {path}")
        self._validate_record_digest(record, path)
        if record["state"] in _RESULT_STATES:
            if int(record.get("session_count", -1)) != group_size:
                raise PartialRolloutError(f"partial result session count mismatch: {path}")
            self._validate_blob_reference(record, path)
        if (
            record["state"] == STATE_KEEP
            and int(record.get("accepted_rollout_id", -1)) != self.header.rollout_id
        ):
            raise PartialRolloutError(f"partial KEEP rollout mismatch: {path}")
        if record["state"] == STATE_DROP and not str(record.get("drop_outcome", "")).strip():
            raise PartialRolloutError(f"partial DROP outcome is missing: {path}")

    def load_records(self) -> list[dict[str, Any]]:
        with self._lock:
            if not self.directory.exists():
                return []
            records: list[dict[str, Any]] = []
            for path in sorted(self.directory.glob("reservation_*.pt")):
                try:
                    record = torch.load(path, weights_only=False)
                except Exception as exc:
                    raise PartialRolloutError(f"cannot load partial record {path}: {exc}") from exc
                self._validate_record(record, path)
                records.append(record)

            reservation_ids = [int(record["reservation_id"]) for record in records]
            if reservation_ids:
                expected = list(range(reservation_ids[0], reservation_ids[-1] + 1))
                if reservation_ids != expected:
                    raise PartialRolloutError(
                        "partial reservation WAL is not a contiguous allocation prefix: "
                        f"actual={reservation_ids}, expected={expected}"
                    )
            keep_count = sum(record["state"] == STATE_KEEP for record in records)
            if keep_count > self.header.target_groups:
                raise PartialRolloutError(
                    f"partial WAL contains {keep_count} KEEP groups for target "
                    f"{self.header.target_groups}"
                )
            self._validate_ready_marker(records)
            return records

    def _validate_ready_marker(self, records: list[dict[str, Any]]) -> None:
        path = self._ready_path()
        if not path.exists():
            return
        try:
            marker = torch.load(path, weights_only=False)
        except Exception as exc:
            raise PartialRolloutError(f"cannot load READY marker {path}: {exc}") from exc
        if not isinstance(marker, dict):
            raise PartialRolloutError(f"READY marker is not a mapping: {path}")
        marker_digest = marker.get("marker_digest")
        unsigned = dict(marker)
        unsigned.pop("marker_digest", None)
        if marker_digest != _canonical_digest(unsigned):
            raise PartialRolloutError(f"READY marker digest mismatch: {path}")
        if marker.get("version") != PARTIAL_ROLLOUT_WAL_VERSION:
            raise PartialRolloutError(f"READY marker version mismatch: {path}")
        if marker.get("header") != self.header.to_dict():
            raise PartialRolloutError(f"READY marker header mismatch: {path}")
        keep_ids = sorted(
            int(record["reservation_id"]) for record in records if record["state"] == STATE_KEEP
        )
        if marker.get("accepted_reservation_ids") != keep_ids:
            raise PartialRolloutError(f"READY marker KEEP set mismatch: {path}")
        if len(keep_ids) != self.header.target_groups:
            raise PartialRolloutError(f"READY marker has incomplete batch: {path}")
        self._sealed = True

    def record_prepared(
        self,
        *,
        reservation_id: int,
        group: list[Any],
        submitted_rollout_id: int,
        policy_version: int,
    ) -> None:
        with self._lock:
            if self._sealed:
                return
            digest = prompt_group_digest(group)
            current = self._load_record(reservation_id)
            if current is not None:
                identity = (
                    current["prompt_digest"] == digest
                    and int(current["submitted_rollout_id"]) == int(submitted_rollout_id)
                    and int(current["policy_version"]) == int(policy_version)
                )
                if not identity:
                    raise PartialRolloutError(
                        f"reservation {reservation_id} was prepared with different identity"
                    )
                return
            record = self._base_record(
                reservation_id=reservation_id,
                state=STATE_PREPARED,
                prompt_digest=digest,
                submitted_rollout_id=submitted_rollout_id,
                policy_version=policy_version,
                group_size=len(group),
            )
            _atomic_torch_save(
                self._with_record_digest(record),
                self._record_path(reservation_id),
            )

    def _write_sample_blob(self, reservation_id: int, samples: list[Any]) -> dict[str, Any]:
        self.directory.mkdir(parents=True, exist_ok=True)
        temporary = self.directory / (
            f"samples_{int(reservation_id):020d}.tmp.{os.getpid()}.{threading.get_ident()}"
        )
        sample_dicts = [_sample_to_dict(sample) for sample in samples]
        semantic_digest = _canonical_digest(sample_dicts)
        payload = {
            "version": PARTIAL_ROLLOUT_WAL_VERSION,
            "reservation_id": int(reservation_id),
            "semantic_sha256": semantic_digest,
            "samples": sample_dicts,
        }
        try:
            with open(temporary, "wb") as stream:
                torch.save(payload, stream)
                stream.flush()
                os.fsync(stream.fileno())
            digest = _sha256_file(temporary)
            destination = self.directory / (f"samples_{int(reservation_id):020d}_{digest}.pt")
            if destination.exists():
                if _sha256_file(destination) != digest:
                    raise PartialRolloutError(f"existing sample blob is corrupt: {destination}")
            else:
                os.replace(temporary, destination)
                _fsync_directory(self.directory)
            return {
                "name": destination.name,
                "sha256": digest,
                "semantic_sha256": semantic_digest,
                "sample_count": len(samples),
            }
        finally:
            try:
                temporary.unlink()
            except FileNotFoundError:
                pass

    def record_result_ready(self, completed: Any) -> None:
        reservation_id = completed.reservation_id
        if reservation_id is None:
            return
        with self._lock:
            if self._sealed:
                return
            current = self._load_record(reservation_id)
            if current is None:
                raise PartialRolloutError(
                    f"result arrived before PREPARED for reservation {reservation_id}"
                )
            if current["state"] in (STATE_RESULT_READY, STATE_KEEP):
                actual_digest = _canonical_digest(
                    [_sample_to_dict(sample) for sample in completed.samples]
                )
                if current["sample_blob"].get("semantic_sha256") != actual_digest:
                    raise PartialRolloutError(
                        f"conflicting result payload for reservation {reservation_id}"
                    )
                return
            if current["state"] == STATE_DROP:
                raise PartialRolloutError(
                    f"result arrived after DROP for reservation {reservation_id}"
                )
            if current["state"] != STATE_PREPARED:
                raise PartialRolloutError(f"illegal result transition from {current['state']}")
            blob = self._write_sample_blob(reservation_id, completed.samples)
            record = dict(current)
            record.update(
                {
                    "state": STATE_RESULT_READY,
                    "sample_blob": blob,
                    "task_id": str(completed.task_id),
                    "scheduler_group_id": int(completed.group_id),
                    "session_count": int(completed.session_count),
                    "service_time_seconds": float(completed.service_time_seconds),
                    "sample_conversion_seconds": float(completed.sample_conversion_seconds),
                    "updated_unix_ns": time.time_ns(),
                }
            )
            _atomic_torch_save(
                self._with_record_digest(record),
                self._record_path(reservation_id),
            )

    def record_keep(self, completed: Any, *, accepted_rollout_id: int) -> None:
        reservation_id = completed.reservation_id
        if reservation_id is None:
            return
        with self._lock:
            if self._sealed:
                return
            current = self._load_record(reservation_id)
            if current is None or current["state"] not in (
                STATE_RESULT_READY,
                STATE_KEEP,
            ):
                raise PartialRolloutError(
                    f"KEEP requires RESULT_READY for reservation {reservation_id}"
                )
            if current["state"] == STATE_KEEP:
                if int(current["accepted_rollout_id"]) != int(accepted_rollout_id):
                    raise PartialRolloutError(
                        f"reservation {reservation_id} was kept by another rollout"
                    )
                actual_digest = _canonical_digest(
                    [_sample_to_dict(sample) for sample in completed.samples]
                )
                if current["sample_blob"].get("semantic_sha256") != actual_digest:
                    raise PartialRolloutError(
                        f"conflicting KEEP payload for reservation {reservation_id}"
                    )
                return
            # RESULT_READY is written before scheduler annotation and the
            # dynamic filter.  Persist the exact post-filter, annotated sample
            # objects that will be handed to the optimizer.
            accepted_blob = self._write_sample_blob(reservation_id, completed.samples)
            record = dict(current)
            record.update(
                {
                    "state": STATE_KEEP,
                    "accepted_rollout_id": int(accepted_rollout_id),
                    "sample_blob": accepted_blob,
                    "updated_unix_ns": time.time_ns(),
                }
            )
            _atomic_torch_save(
                self._with_record_digest(record),
                self._record_path(reservation_id),
            )

    def record_drop(
        self,
        reservation_id: int | None,
        *,
        outcome: str,
        reason: str | None = None,
    ) -> None:
        if reservation_id is None:
            return
        with self._lock:
            if self._sealed:
                return
            current = self._load_record(reservation_id)
            if current is None:
                raise PartialRolloutError(
                    f"DROP arrived before PREPARED for reservation {reservation_id}"
                )
            if current["state"] == STATE_KEEP:
                raise PartialRolloutError(f"cannot DROP kept reservation {reservation_id}")
            if current["state"] == STATE_DROP:
                if current.get("drop_outcome") != outcome or current.get("drop_reason") != reason:
                    raise PartialRolloutError(
                        f"conflicting DROP decision for reservation {reservation_id}"
                    )
                return
            record = dict(current)
            record.update(
                {
                    "state": STATE_DROP,
                    "drop_outcome": str(outcome),
                    "drop_reason": reason,
                    "updated_unix_ns": time.time_ns(),
                }
            )
            _atomic_torch_save(
                self._with_record_digest(record),
                self._record_path(reservation_id),
            )

    def mark_ready(self, accepted_reservation_ids: Iterable[int | None]) -> None:
        ids = sorted(int(item) for item in accepted_reservation_ids if item is not None)
        with self._lock:
            records = self.load_records()
            keep_ids = sorted(
                int(record["reservation_id"])
                for record in records
                if record["state"] == STATE_KEEP
            )
            if ids != keep_ids or len(ids) != self.header.target_groups:
                raise PartialRolloutError(
                    "cannot seal partial WAL before exactly one complete KEEP batch: "
                    f"accepted={ids}, durable_keep={keep_ids}, "
                    f"target={self.header.target_groups}"
                )
            marker = {
                "version": PARTIAL_ROLLOUT_WAL_VERSION,
                "header": self.header.to_dict(),
                "accepted_reservation_ids": ids,
                "created_unix_ns": time.time_ns(),
            }
            marker["marker_digest"] = _canonical_digest(marker)
            _atomic_torch_save(marker, self._ready_path())
            self._sealed = True

    def _validate_blob_reference(self, record: dict[str, Any], record_path: Path) -> None:
        blob = record.get("sample_blob")
        if not isinstance(blob, dict):
            raise PartialRolloutError(f"missing sample blob reference: {record_path}")
        name = blob.get("name")
        digest = blob.get("sha256")
        if (
            not isinstance(name, str)
            or Path(name).name != name
            or not isinstance(digest, str)
            or len(digest) != 64
            or not isinstance(blob.get("semantic_sha256"), str)
            or len(blob["semantic_sha256"]) != 64
        ):
            raise PartialRolloutError(f"invalid sample blob reference: {record_path}")
        path = self.directory / name
        if not path.is_file() or _sha256_file(path) != digest:
            raise PartialRolloutError(f"sample blob missing or corrupt: {path}")

    def load_sample_dicts(self, record: dict[str, Any]) -> list[dict[str, Any]]:
        with self._lock:
            self._validate_blob_reference(record, self._record_path(record["reservation_id"]))
            path = self.directory / record["sample_blob"]["name"]
            try:
                payload = torch.load(path, weights_only=False)
            except Exception as exc:
                raise PartialRolloutError(f"cannot load sample blob {path}: {exc}") from exc
            if (
                not isinstance(payload, dict)
                or payload.get("version") != PARTIAL_ROLLOUT_WAL_VERSION
                or int(payload.get("reservation_id", -1)) != int(record["reservation_id"])
                or payload.get("semantic_sha256") != record["sample_blob"]["semantic_sha256"]
                or not isinstance(payload.get("samples"), list)
                or len(payload["samples"]) != int(record["sample_blob"]["sample_count"])
                or not all(isinstance(sample, dict) for sample in payload["samples"])
                or _canonical_digest(payload["samples"])
                != record["sample_blob"]["semantic_sha256"]
            ):
                raise PartialRolloutError(f"invalid sample blob payload: {path}")
            return payload["samples"]

    def quarantine(self, reason: str) -> Path | None:
        """Atomically move an untrusted WAL aside before at-least-once replay."""

        with self._lock:
            if not self.directory.exists():
                return None
            suffix = hashlib.sha256(reason.encode("utf-8", errors="replace")).hexdigest()[:10]
            destination = self.directory.with_name(
                f"{self.directory.name}.invalid.{time.time_ns()}.{os.getpid()}.{suffix}"
            )
            os.replace(self.directory, destination)
            _fsync_directory(destination.parent)
            self._sealed = True
            logger.error("Quarantined invalid partial rollout WAL at %s: %s", destination, reason)
            return destination
