#!/usr/bin/env bash
# One-node, one-optimizer-step SPilot integration smoke before the 8-node run.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
SPILOT_ROOT="$(cd -- "${PROJECT_ROOT}/../.." && pwd)"

export POLAR_DATA_ROOT="${POLAR_DATA_ROOT:-${SPILOT_ROOT}/data}"
export TMAX_RUN_STATE_FILE="${TMAX_RUN_STATE_FILE:-${POLAR_DATA_ROOT}/runs/spilot_router_slime_grpo/smoke_current_run.env}"

export NUM_NODES="${NUM_NODES:-1}"
export ACTOR_NUM_NODES="${ACTOR_NUM_NODES:-1}"
export ACTOR_NUM_GPUS_PER_NODE="${ACTOR_NUM_GPUS_PER_NODE:-4}"
export ACTOR_TENSOR_MODEL_PARALLEL_SIZE="${ACTOR_TENSOR_MODEL_PARALLEL_SIZE:-4}"
export ROLLOUT_NUM_GPUS="${ROLLOUT_NUM_GPUS:-4}"
export ROLLOUT_NUM_GPUS_PER_ENGINE="${ROLLOUT_NUM_GPUS_PER_ENGINE:-1}"
export MAX_TOKENS_PER_GPU="${MAX_TOKENS_PER_GPU:-24576}"
export TMAX_ALLOW_SINGLE_SAMPLE_OVER_TOKEN_CAP="${TMAX_ALLOW_SINGLE_SAMPLE_OVER_TOKEN_CAP:-1}"
export TMAX_OPTIMIZER_CPU_OFFLOAD="${TMAX_OPTIMIZER_CPU_OFFLOAD:-1}"

export ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE:-1}"
export N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT:-8}"
export GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-8}"
export EVAL_GLOBAL_BATCH_SIZE="${EVAL_GLOBAL_BATCH_SIZE:-8}"
export POLAR_FULLY_ASYNC="${POLAR_FULLY_ASYNC:-false}"
export POLAR_MAX_ASYNC_LEVEL="${POLAR_MAX_ASYNC_LEVEL:-1}"
export POLAR_MIN_COMPLETE_ACCEPT_FRACTION="${POLAR_MIN_COMPLETE_ACCEPT_FRACTION:-0}"
export POLAR_EARLY_STOP_GRACE_SESSIONS="${POLAR_EARLY_STOP_GRACE_SESSIONS:-0}"
export POLAR_MAX_INIT_WORKERS="${POLAR_MAX_INIT_WORKERS:-4}"
export POLAR_MAX_RUN_WORKERS="${POLAR_MAX_RUN_WORKERS:-4}"
export POLAR_MAX_POSTRUN_WORKERS="${POLAR_MAX_POSTRUN_WORKERS:-4}"

export TMAX_NUM_ROLLOUT="${TMAX_NUM_ROLLOUT:-1}"
export SAVE_INTERVAL="${SAVE_INTERVAL:-1}"
export TMAX_DYNAMIC_SAMPLING_FILTER_PATH=""
export TMAX_EVAL_ENABLED="${TMAX_EVAL_ENABLED:-0}"
export TMAX_TRAINING_EVAL_ENABLED="${TMAX_TRAINING_EVAL_ENABLED:-0}"
export TMAX_EXTERNAL_EVAL_ENABLED="${TMAX_EXTERNAL_EVAL_ENABLED:-0}"
export TMAX_MAX_TASKS="${TMAX_MAX_TASKS:-8}"
export TMAX_TOTAL_TASKS="${TMAX_TOTAL_TASKS:-8}"
export TMAX_REQUIRE_EXACT_TOTAL_TASKS="${TMAX_REQUIRE_EXACT_TOTAL_TASKS:-0}"
# A smoke deliberately selects the first small slice instead of rebuilding the
# complete formal train set.  The full-run holdout exclusion contract only
# supports the complete start=0/max=-1 dataset, so do not inherit it here.
export TMAX_EXCLUDE_DATA=""

export WALL_TIME="${WALL_TIME:-1-00:00:00}"
export TMAX_MIN_WALL_TIME="${TMAX_MIN_WALL_TIME:-1-00:00:00}"
export TMAX_GRACEFUL_EXIT_BUFFER_SECONDS="${TMAX_GRACEFUL_EXIT_BUFFER_SECONDS:-43200}"
export TMAX_MIN_GRACEFUL_EXIT_BUFFER_SECONDS="${TMAX_MIN_GRACEFUL_EXIT_BUFFER_SECONDS:-43200}"
export EXPERIMENT_NAME="${EXPERIMENT_NAME:-spilot-router-qwen35-9b-1n-smoke}"

exec bash "${SCRIPT_DIR}/submit_slurm.sh" "$@"
